import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Cookies from 'js-cookie'

import { api } from "../services/api"

import Header from "../components/Header";

import Pagination from "../components/Pagination"
import Cards from "../components/Cards"
import GameSearch from "../components/GameSearch"
interface Item {
  developer: string,
  freetogame_profile_url: string,
  game_url: string,
  genre: string,
  id: number,
  platform: string,
  publisher: String,
  release_date: string,
  short_description: string,
  thumbnail: string,
  title: string
}
const Home: NextPage = () => {
  


  return (
    <>
      <Head>
        <title>App Mastters</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {/* <Header/> */}
      <main>
        <GameSearch/>
        


      </main>
  </>
  )
}
// export const getStaticProps: GetStaticProps = async () => {



//     const { data } = await api.get("/games");
    
//     // console.log("items", response)
//     // const data = response.data

//   return {
//     props: {
//       data

//     },
//   };
// };


export default Home
